version: "3.7"
services:
  web-server:
    build:
      dockerfile: php.Dockerfile
      context: .
    restart: always
    volumes:
      - "./certs/ssl/:/etc/apache2/ssl/"
      - "./Responder/logs/:/var/log/Responder/"
    ports:
      - "80:80"
      - "443:443"
  python:
    build:
      dockerfile: python.Dockerfile
      context: .
    restart: always
    volumes:
      - "./Responder/logs/:/var/log/Responder/"
    ports:
      - "445:445"
      - "137:137"
      - "138:138"
      - "139:139"
  mysql-server:
    build:
      dockerfile: mysql.Dockerfile
      context: .
    image: mysql:8.0.19
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: PhishAPIDef@ulT
      DB_HOST: 
    volumes:
      - mysql-data:/var/lib/mysql
      - "./db/:/docker-entrypoint-initdb.d/"
volumes:
  mysql-data:
